MEMBERSHIP_ID_NAME:
  BASIC: 'Basic member'
  ACTIVE: 'Active member'
  PREMIUM: 'Premium member'
MEMBERSHIP_ID:
  BASIC: 'BASIC'
  ACTIVE: 'ACTIVE'
  PREMIUM: 'PREMIUM'
GUEST_SESSION_COUNT: 1
UPGRADE_CONFIG:
  ACCOUNT_LIFE: 10
  MONTHLY_SESSION: 5
KEEP_ACTIVE_CONFIG:
  MONTHLY_SESSION: 7