USER_GROUP:
  GUEST:
    SESSION_COUNT: 1
    MONTHLY_COUNT: 99999
  MEMBER:
    SESSION_COUNT: 10
    MONTHLY_COUNT: 10
  ACTIVE_MEMBER:
    SESSION_COUNT: 5
    MONTHLY_COUNT: 20
  PREMIUM:
    SESSION_COUNT: 10
    MONTHLY_COUNT: 50
SESSION_COUNT:
  GUEST: 1
  REGISTERED: 10
  PREMIUM: 5
  VIP: 10